name: Build & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Example - helloworld
        run: go build examples/helloworld/helloworld.go

      - name: Example - requestbody
        run: go build examples/requestbody/printpost.go

      - name: Example - pathgroups
        run: go build examples/pathgroups/pathgroups.go

      - name: Example - middlewares
        run: go build examples/middlewares/middlewares.go

      - name: Tests
        run: go test -v ./...