name: Build & Test

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
      - workflow/ci

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Run tests
        run: go test -race ./...