name: Build & Test

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
      - workflow/ci

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install deepsource CLI tool
        run: curl https://deepsource.io/cli | sh
      
      - name: Run tests
        run: go test -coverprofile=cover.out ./...

      - name: Run tests with -race option
        run: go test -race ./...

      - name: Code coverage report
        run: |
          ./bin/deepsource report --analyzer test-coverage --key go --value-file ./cover.out
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
